spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tripsplit
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

server:
  error:
    whitelabel:
      enabled: false
